// <auto-generated />
namespace ass2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SmartLookupAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SmartLookupAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201503052201349_SmartLookupAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
